spring.application.name: ApiGateway

server.port: 8080

# jwt secret key
jwt:
  secretKey: dakfjladsjflajsdfljasdlfjadslgvhnkjabrkgjvhjkfbrfbdkj

# eureka client configurations
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


# routes, predicates, filters
spring:
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

        - id: PostService
          uri: lb://POSTSERVICE
          predicates:
            - Path=/api/v1/posts/**
            - Path=/api/v1/likes/**
          filters:
            - StripPrefix=2
            - name: AuthFilter

        - id: ConnectionService
          uri: lb://CONNECTIONSERVICE
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthFilter






